name: flutter_dev_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.1.0+1
#  background_fetch: ^1.1.6
  path_provider: ^2.0.15
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Functional programming things
  dartz: ^0.10.1
  # Service locator
  get_it: ^7.6.0
  # Remote API
  internet_connection_checker: ^1.0.0+1
  # Local cache
  shared_preferences: ^2.1.1
  http: ^1.1.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

